# Generated by Django 4.2.11 on 2024-04-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0006_acc_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc_details',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acc_details',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
