# Generated by Django 4.2.11 on 2024-04-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0007_acc_details_email_acc_details_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc_details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
