# Generated by Django 4.2.11 on 2024-04-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0008_acc_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='acc_details',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
