# Generated by Django 4.2.11 on 2024-04-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0009_alter_acc_details_image_alter_acc_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
