# Generated by Django 4.2.11 on 2024-04-17 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0010_alter_acc_details_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_number', models.CharField(default='-1', max_length=100, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('topic', models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Technical Support', 'Technical Support'), ('Billing Issue', 'Billing Issue'), ('Other', 'Other')], max_length=30)),
                ('message', models.CharField(max_length=1000)),
                ('timestamp_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_read', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('actions', models.CharField(choices=[('Awaiting Review', 'Awaiting Review'), ('Responded', 'Responded'), ('Escalated', 'Escalated')], default='Awaiting Review', max_length=20)),
            ],
        ),
    ]
