# Generated by Django 4.2.11 on 2024-04-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0012_alter_messages_timestamp_read_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='message_body',
        ),
    ]
