# Generated by Django 4.2.11 on 2024-04-26 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0014_alter_messages_timestamp_read_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCentreMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_number', models.UUIDField(default='-1', unique=True)),
                ('subject', models.CharField(max_length=50)),
                ('topic', models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Technical Support', 'Technical Support'), ('Billing Issue', 'Billing Issue'), ('Other', 'Other')], max_length=30)),
                ('message_body', models.CharField(max_length=1000)),
                ('timestamp_sent', models.DateTimeField()),
                ('timestamp_read', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('actions', models.CharField(choices=[('Awaiting Review', 'Awaiting Review'), ('Responded', 'Responded'), ('Escalated', 'Escalated')], default='Awaiting Review', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TerminateAccountMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Poor Service', 'Poor Service'), ('Found A Better Service', 'Found A Better Service'), ('Privacy Concerns', 'Privacy Concerns'), ('Other', 'Other')], max_length=50)),
                ('message_body', models.CharField(max_length=1000)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('user_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rpm', models.IntegerField(blank=True, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('incline', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.UUIDField(default='-1', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_server.user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VRGame', 'VRGame'), ('Cycling', 'Cycling'), ('Running', 'Running'), ('Yoga', 'Yoga'), ('Pilates', 'Pilates'), ('Aerobic', 'Aerobic'), ('High Intensity', 'High Intensity')], max_length=20)),
                ('session_duration', models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes')])),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('type', models.CharField(choices=[('Interval', 'Interval'), ('Continuous', 'Continuous')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='acc_details',
        ),
        migrations.DeleteModel(
            name='messages',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='warehouse',
        ),
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend_server.user')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='workoutentry',
            name='workout_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_server.workouttype'),
        ),
        migrations.AddField(
            model_name='helpcentremessage',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_server.user'),
        ),
    ]
