# Generated by Django 4.2.11 on 2024-04-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0016_alter_user_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_created',
            field=models.DateTimeField(max_length=50, null=True),
        ),
    ]
