# Generated by Django 4.2.11 on 2024-04-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0019_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
