# Generated by Django 4.2.11 on 2024-04-27 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0021_rename_user_email_accountdetails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='email_accountdetails', serialize=False, to='backend_server.myuser'),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='username_accountdetails', to='backend_server.myuser', to_field='username'),
        ),
    ]
