# Generated by Django 4.2.11 on 2024-04-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0022_alter_accountdetails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
