# Generated by Django 4.2.11 on 2024-05-02 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0025_workouttype_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_server.myuser'),
        ),
    ]
