# Generated by Django 4.2.11 on 2024-05-02 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0027_alter_workoutentry_workout_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutentry',
            name='workout_type',
        ),
        migrations.AddField(
            model_name='workoutentry',
            name='user_email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend_server.myuser'),
        ),
    ]
