# Generated by Django 4.2.11 on 2024-05-02 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0028_remove_workoutentry_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutentry',
            name='user_email',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='backend_server.myuser'),
        ),
    ]
