# Generated by Django 4.2.11 on 2024-05-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0029_alter_workoutentry_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutentry',
            name='session_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='backend_server.workouttype', to_field='session_id'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='session_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
