# Generated by Django 4.2.11 on 2024-05-02 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0030_alter_workoutentry_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutentry',
            name='session_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='backend_server.workouttype', to_field='session_id'),
        ),
    ]
