# Generated by Django 4.2.11 on 2024-05-03 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0032_remove_workoutentry_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutentry',
            name='id',
        ),
        migrations.AddField(
            model_name='workoutentry',
            name='session_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='session_id_workouttype', serialize=False, to='backend_server.workouttype'),
            preserve_default=False,
        ),
    ]
