# Generated by Django 4.2.11 on 2024-05-03 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0033_remove_workoutentry_id_workoutentry_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutentry',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='session_id_workouttype', serialize=False, to='backend_server.workouttype'),
        ),
    ]
