# Generated by Django 4.2.11 on 2024-05-03 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0034_alter_workoutentry_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutentry',
            name='email',
        ),
        migrations.AddField(
            model_name='workoutentry',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouttype',
            name='email',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='backend_server.myuser'),
        ),
        migrations.AlterField(
            model_name='workoutentry',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_id_workouttype', to='backend_server.workouttype'),
        ),
    ]
