# Generated by Django 4.2.11 on 2024-05-03 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0035_remove_workoutentry_email_workoutentry_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttype',
            name='email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend_server.myuser'),
        ),
    ]
