# Generated by Django 5.0.6 on 2024-05-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0037_workouttype_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='login_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='login_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
