# Generated by Django 5.0.6 on 2024-05-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend_server", "0038_myuser_login_id_myuser_login_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workouttype",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
