# Generated by Django 5.0.6 on 2024-05-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend_server", "0041_workouttype_finished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutanalysis",
            name="workout_duration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
