# Generated by Django 5.0.6 on 2024-05-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend_server", "0042_alter_workoutanalysis_workout_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutanalysis",
            name="workout_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
