# Generated by Django 5.0.6 on 2024-09-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0043_alter_workoutanalysis_workout_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
